# Generated by Django 3.2.16 on 2023-02-25 20:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Inst_ID', models.CharField(max_length=10)),
                ('Instructor_Name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('School', models.CharField(blank=True, max_length=40, null=True)),
                ('Programme_ID', models.CharField(max_length=10)),
                ('Programme_Name', models.CharField(max_length=40)),
                ('Programme_YearandSemester', models.CharField(choices=[('1st Year/ SEMESTER 1', '1st Year/ SEMESTER 1'), ('1st Year/ SEMESTER 2', '1st Year/ SEMESTER 2'), ('2nd Year/ SEMESTER 3', '2nd Year/ SEMESTER 3'), ('2nd Year/ SEMESTER 4', '2nd Year/ SEMESTER 4'), ('3rd Year/ SEMESTER 5', '3rd Year/ SEMESTER 5'), ('3rd Year/ SEMESTER 6', '3rd Year/ SEMESTER 6'), ('4th Year/ SEMESTER 7', '4th Year/ SEMESTER 7'), ('4th Year/ SEMESTER 8', '4th Year/ SEMESTER 8')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Room_ID', models.CharField(max_length=10)),
                ('Room_Capacity', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Timeslot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Meet_ID', models.CharField(max_length=10)),
                ('Slots', models.CharField(choices=[('9:30 - 10:30', '9:30 - 10:30'), ('10:30 - 11:30', '10:30 - 11:30'), ('11:30 - 12:30', '11:30 - 12:30'), ('12:30 - 1:30', '12:30 - 1:30'), ('2:30 - 3:30', '2:30 - 3:30'), ('3:30 - 4:30', '3:30 - 4:30'), ('4:30 - 5:30', '4:30 - 5:30')], max_length=13)),
                ('Days', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_ID', models.CharField(max_length=10)),
                ('Course_Name', models.CharField(max_length=40)),
                ('Course_Capacity', models.PositiveIntegerField(default=0)),
                ('Course_Semester', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(6), django.core.validators.MinValueValidator(1)])),
                ('Course_Instructor', models.ManyToManyField(to='appGen.Instructor')),
                ('programme_Name', models.ManyToManyField(to='appGen.Programme')),
            ],
        ),
    ]
