# Generated by Django 3.2.16 on 2023-02-26 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appGen', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='programme_Name',
            new_name='Programme_Name',
        ),
    ]
